### ISSUE TITLE
rename function

### ISSUE THREAD

**Issue by sjanssen2** [biocore/q2-fragment-insertion#14]
https://github.com/biocore/q2-fragment-insertion/blob/ec8333a62932f312414b670b90a64e1484b75ffd/q2_fragment_insertion/plugin_setup.py#L57

We are now able to pass in other reference trees/alignments. Thus, I think we should rename the QIIME 2 function into something independent of "16S-greengenes", if we intend to compile other references like Silva. Maybe just call it "sepp" ?

@wasade @mortonjt what are your thoughts?

**Comment by wasade** [comment]
+1

On Nov 15, 2017 4:08 PM, "Stefan Janssen" <notifications@github.com> wrote:

https://github.com/biocore/q2-fragment-insertion/blob/
ec8333a62932f312414b670b90a64e1484b75ffd/q2_fragment_
insertion/plugin_setup.py#L57

We are now able to pass in other reference trees/alignments. Thus, I think
we should rename the QIIME 2 function into something independent of
"16S-greengenes", if we intend to compile other references like Silva.
Maybe just call it "sepp" ?

@wasade <https://github.com/wasade> @mortonjt <https://github.com/mortonjt>
what are your thoughts?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/biocore/q2-fragment-insertion/issues/14>, or mute the
thread

**Comment by sjanssen2** [comment]
fixed
