### ISSUE TITLE
"no action filter-features" qiime fragment-insertion filter-features 

### ISSUE THREAD

**Issue by courtneystairs** [biocore/q2-fragment-insertion#39]
Hi there, 

I stumbled on a weird behaviour with `qiime fragment-insertions` where why I run the following I get an error that it cannot file the 'filter-features' option.  

```
qiime fragment-insertion filter-features \
  --i-table $path2table \
  --i-tree insertion-tree.qza \
  --o-filtered-table filtered_table.qza \
  --o-removed-table removed_table.qza
```
Returns the following error:

> Error: QIIME 2 plugin 'fragment-insertion' has no action 'filter-features'.

Further, if I look at the `qiime fragment-insertion --help` there are only two options `classify-otus-experimental`  and `sepp`

I would be very grateful for any help you could provide.  I'm an amateur bioinformatician and I have now exhausted my troubleshooting skills.

I am running QIIME 2 version 2018.4.0 with fragment-insterion 2018.2.0.dev0. See attached for my complete `qiime info` output. 

Thank you very much for your help (and the easy-to-use software!!)

Courtney

[qiime_version.txt](https://github.com/biocore/q2-fragment-insertion/files/2123965/qiime_version.txt)

**Comment by sjanssen2** [comment]
Hi Courtney,
this is totally my fault. Today, I am in the process to update the plugin. The github pages already mention the new function that you want to use, but I have not yet managed to build and upload updated packages to anaconda.
Please be a little patient until I push the packages. You should than be able to conda install a newer version 2018.6 which will have this new function.

Best,
Stefan

P.S. it would be more suitable to post those kinds of questions at forum.qiime2.org, because it would draw more attention + is the no. 1 source for user help for Qiime2 related topics.

**Comment by sjanssen2** [comment]
you should now be able to install the new version `conda install -c anaconda -c defaults -c conda-forge -c bioconda -c https://conda.anaconda.org/biocore q2-fragment-insertion=2018.6`
Let me know if you still have trouble, as you might be the very first user.
